<a href="https://colab.research.google.com/github/tonyyucrachurata-dev/el-buen-sabor-mvp/blob/main/TAL_RNA_004.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

------ CLASIFICAIÓN BINARIA DE PROGRAMADORES PARA EL CARGO LABORAL----

In [23]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder, LabelBinarizer

In [24]:
postulantes= pd.DataFrame({
    'lenguaje':['java','js','php','java','java','php','js','java'],
    'perfil':['back','front','back','back','back','back','front','back'],
    'exp':[5, 1, 3, 1, 3, 5, 5, 2],
    'sueldo':[5000, 1000,3000,1000,3000,5000,5000,2000],
    'estado':['apto','no apto','no apto','no apto','apto','no apto','no apto','no apto']
})
postulantes

,lenguaje,perfil,exp,sueldo,estado
0,java,back,5,5000,apto
1,js,front,1,1000,no apto
2,php,back,3,3000,no apto
3,java,back,1,1000,no apto
4,java,back,3,3000,apto
5,php,back,5,5000,no apto
6,js,front,5,5000,no apto
7,java,back,2,2000,no apto


In [25]:
x_cat = postulantes[['lenguaje','perfil']]
x_cat

,lenguaje,perfil
0,java,back
1,js,front
2,php,back
3,java,back
4,java,back
5,php,back
6,js,front
7,java,back


In [26]:
x_num = postulantes[['exp','sueldo']]
x_num

,exp,sueldo
0,5,5000
1,1,1000
2,3,3000
3,1,1000
4,3,3000
5,5,5000
6,5,5000
7,2,2000


In [27]:
y_bin = postulantes[['estado']]
y_bin

,estado
0,apto
1,no apto
2,no apto
3,no apto
4,apto
5,no apto
6,no apto
7,no apto


In [28]:
cat_encoder = OneHotEncoder(sparse_output= False) #PARA VARIABLES CATEGÓRICAS NOMINALES
num_scaler = StandardScaler() #PARA VARIABLES NUMÉRICAS
y_binarizer = LabelBinarizer() #PARA VARIABLES CATEGÓRICAS ORDINALES

In [29]:
x_cat_encoder = cat_encoder.fit_transform(x_cat)
x_cat_encoder

array([[1., 0., 0., 1., 0.],
       [0., 1., 0., 0., 1.],
       [0., 0., 1., 1., 0.],
       [1., 0., 0., 1., 0.],
       [1., 0., 0., 1., 0.],
       [0., 0., 1., 1., 0.],
       [0., 1., 0., 0., 1.],
       [1., 0., 0., 1., 0.]])

In [30]:
x_num_scaler = num_scaler.fit_transform(x_num)
x_num_scaler

array([[ 1.16073485,  1.16073485],
       [-1.3154995 , -1.3154995 ],
       [-0.07738232, -0.07738232],
       [-1.3154995 , -1.3154995 ],
       [-0.07738232, -0.07738232],
       [ 1.16073485,  1.16073485],
       [ 1.16073485,  1.16073485],
       [-0.69644091, -0.69644091]])

In [31]:
y_binarizer = y_binarizer.fit_transform(y_bin)
y_binarizer

array([[0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1]])

In [33]:
postulantes_normalizer = np.hstack((x_cat_encoder,x_num_scaler,y_binarizer))
postulantes_normalizer

array([[ 1.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         1.16073485,  1.16073485,  0.        ],
       [ 0.        ,  1.        ,  0.        ,  0.        ,  1.        ,
        -1.3154995 , -1.3154995 ,  1.        ],
       [ 0.        ,  0.        ,  1.        ,  1.        ,  0.        ,
        -0.07738232, -0.07738232,  1.        ],
       [ 1.        ,  0.        ,  0.        ,  1.        ,  0.        ,
        -1.3154995 , -1.3154995 ,  1.        ],
       [ 1.        ,  0.        ,  0.        ,  1.        ,  0.        ,
        -0.07738232, -0.07738232,  0.        ],
       [ 0.        ,  0.        ,  1.        ,  1.        ,  0.        ,
         1.16073485,  1.16073485,  1.        ],
       [ 0.        ,  1.        ,  0.        ,  0.        ,  1.        ,
         1.16073485,  1.16073485,  1.        ],
       [ 1.        ,  0.        ,  0.        ,  1.        ,  0.        ,
        -0.69644091, -0.69644091,  1.        ]])

In [34]:
planilla_pandas = pd.DataFrame(postulantes_normalizer)
planilla_pandas

,0,1,2,3,4,5,6,7
0,1.0,0.0,0.0,1.0,0.0,1.160735,1.160735,0.0
1,0.0,1.0,0.0,0.0,1.0,-1.315499,-1.315499,1.0
2,0.0,0.0,1.0,1.0,0.0,-0.077382,-0.077382,1.0
3,1.0,0.0,0.0,1.0,0.0,-1.315499,-1.315499,1.0
4,1.0,0.0,0.0,1.0,0.0,-0.077382,-0.077382,0.0
5,0.0,0.0,1.0,1.0,0.0,1.160735,1.160735,1.0
6,0.0,1.0,0.0,0.0,1.0,1.160735,1.160735,1.0
7,1.0,0.0,0.0,1.0,0.0,-0.696441,-0.696441,1.0


In [35]:
x = postulantes_normalizer[:, 0:7]
x

array([[ 1.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         1.16073485,  1.16073485],
       [ 0.        ,  1.        ,  0.        ,  0.        ,  1.        ,
        -1.3154995 , -1.3154995 ],
       [ 0.        ,  0.        ,  1.        ,  1.        ,  0.        ,
        -0.07738232, -0.07738232],
       [ 1.        ,  0.        ,  0.        ,  1.        ,  0.        ,
        -1.3154995 , -1.3154995 ],
       [ 1.        ,  0.        ,  0.        ,  1.        ,  0.        ,
        -0.07738232, -0.07738232],
       [ 0.        ,  0.        ,  1.        ,  1.        ,  0.        ,
         1.16073485,  1.16073485],
       [ 0.        ,  1.        ,  0.        ,  0.        ,  1.        ,
         1.16073485,  1.16073485],
       [ 1.        ,  0.        ,  0.        ,  1.        ,  0.        ,
        -0.69644091, -0.69644091]])

In [36]:
y = postulantes_normalizer[:, -1]
y

array([0., 1., 1., 1., 0., 1., 1., 1.])

In [38]:
print(x.shape)
print(y.shape)

(8, 7)
(8,)


In [39]:
import tensorflow as tf


In [42]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(20, activation='relu', input_shape=(7,)),
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [44]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(x, y, epochs=50)

Epoch 1/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.3750 - loss: 0.7946
Epoch 2/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.3750 - loss: 0.7871
Epoch 3/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.3750 - loss: 0.7798
Epoch 4/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.3750 - loss: 0.7726
Epoch 5/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.3750 - loss: 0.7657
Epoch 6/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 0.7589
Epoch 7/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.7521
Epoch 8/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 0.7455
Epoch 9/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5000 - loss: 0.7389
Epoch 10/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5000 - loss: 0.7325
Epoch 11/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.6250 - loss: 0.7261
Epoch 12/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.6250 - loss: 0.7196
Epo

In [49]:
y_pred = model.predict(x)
print('DAtos Reales',y) #Datos Reales
print('Predicciones',np.round(y_pred)) #Predicciones

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
DAtos Reales [0. 1. 1. 1. 0. 1. 1. 1.]
Predicciones [[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [50]:
from sklearn.metrics import accuracy_score, classification_report
print(accuracy_score(y, np.round(y_pred)))
print(classification_report(y, np.round(y_pred)))

0.75
              precision    recall  f1-score   support

         0.0       0.00      0.00      0.00         2
         1.0       0.75      1.00      0.86         6

    accuracy                           0.75         8
   macro avg       0.38      0.50      0.43         8
weighted avg       0.56      0.75      0.64         8



/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
